targets:
  $default:
    builders:
      freezed:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
      source_gen:combining_builder:
        options:
          preamble: |
            // coverage:ignore-file
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
